# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np
Matrix = np.full((5,5),6)
print("Original array:")
print(Matrix)
print("6 on the border and 0 inside in the array")
Matrix[1:-1,1:-1] = 0
print(Matrix)

Original array:
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
6 on the border and 0 inside in the array
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [2]:
# Python program to print nXn Assuming that n is always even as a checkerboard was 

import numpy as np 
def checkboard(n): 
    final = [] 
    for i in range(n): 
        final.append(list(np.tile([3,9],int(n/2))) if i%2==0 else list(np.tile([9,3],int(n/2)))) 
    print(np.array(final)) 

checkboard(8)

[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [3]:
import numpy as np
# Empty array creation
empty_array = np.empty((3,4))
print(empty_array)
# Full array creation
full_array = np.full((3,3),6)
print(full_array)

[[ 1.48543073e-312  0.00000000e+000  8.76794447e+252  2.15895723e+227]
 [ 6.48224638e+170  3.67145870e+228  4.51609076e-144  6.06003395e+233]
 [ 1.06400250e+248  2.26822459e+161  2.89847616e+131 -3.79180528e+120]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees -")
print(F)

#Relation between Centigrade and Farenheat C/5 = (F-32)/9. c = 5(F-32)/9
C = 5*(F - 32)/9
print("Values in  Centigrade degrees -")
print(C)

Values in Fahrenheit degrees -
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees -
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [5]:
import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array x: ",x)
print("Original array y: ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)

Original array x:  [1.+0.j]
Original array y:  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [6]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ", array1)
array2 = [0, 40]
print("Array2: ", array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [7]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1 : ", array1)
array2 = [10, 30, 40]
print("Array2 : ", array2)
print("Common values between two arrays : ")
print(np.intersect1d(array1, array2))

Array1 :  [ 0 10 20 40 60]
Array2 :  [10, 30, 40]
Common values between two arrays : 
[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [8]:
import numpy as np
x = np.array([10, 10, 20, 20, 30, 30])
print("Original array -")
print(x)
print("Unique elements of the above array -")
print(np.unique(x))

x = np.array([[1, 1], [2, 3]])
print("\nOriginal array -")
print(x)
print("Unique elements of the above array -")
print(np.unique(x))

Original array -
[10 10 20 20 30 30]
Unique elements of the above array -
[10 20 30]

Original array -
[[1 1]
 [2 3]]
Unique elements of the above array -
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [9]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ", array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ", array2)
print("\nUnique values that are in only one (not both) of the input arrays -")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]

Unique values that are in only one (not both) of the input arrays -
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [10]:
import numpy as np
#Testing with Boolean Values
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))

#Testing with real values
print(np.all([0, 1, 2, -3]))
print(np.all([1, 2, 3]))

False
True
False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [11]:
import numpy as np
#Testing with Boolean values
print(np.any([[True,True],[True,True]]))
print(np.any([[False,False],[False,False]]))

#Testing with real values
print(np.any([0, 1, 2, -3]))
print(np.any([1, 2, 3]))

True
False
True
True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [12]:
import numpy as np
array = [1, 2, 3, 4]
print("Original array")
print(array)
print("\nRepeating 2 times")
print(np.tile(array, 2))
print("\nRepeating 3 times")
print(np.tile(array, 3))

Original array
[1, 2, 3, 4]

Repeating 2 times
[1 2 3 4 1 2 3 4]

Repeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [13]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6])
print("Original array- ", array)
print("Indices of Maximum Values- ", np.argmax(array))
print("Indices of Minimum Values- ", np.argmin(array))

Original array-  [1 2 3 4 5 6]
Indices of Maximum Values-  5
Indices of Minimum Values-  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [14]:
import numpy as np
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a- ",a)
print("Array b- ",b)
print("\na > b")
print(np.greater(a, b))
print("\na >= b")
print(np.greater_equal(a, b))
print("\na < b")
print(np.less(a, b))
print("\na <= b")
print(np.less_equal(a, b))

Array a-  [1 2]
Array b-  [4 5]

a > b
[False False]

a >= b
[False False]

a < b
[ True  True]

a <= b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [15]:
import numpy as np
array = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(array)
print("\nSort along the first axis: ")
sort_array = np.sort(array, axis=0)
print(sort_array)
print("\nSort along the last axis- ")
sorted_array = np.sort(sort_array, axis=1)
print(sorted_array)

Original array: 
[[4 6]
 [2 1]]

Sort along the first axis: 
[[2 1]
 [4 6]]

Sort along the last axis- 
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [16]:
import numpy as np
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')

''' order to get the desred output 1,3,2,4,0
#need to consider the first name and last names as follows
#Otherwise output will be 0,1,2,3,4'''

first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')

sorted_pair = np.lexsort((first_names, last_names))
print(sorted_pair)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [17]:
import numpy as np
array = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array - ")
print(array)
print("\nValues bigger than 10 =", array[array > 10])
print("\nTheir indices are ", np.nonzero(array > 10))

Original array - 
[[ 0 10 20]
 [20 30 40]]

Values bigger than 10 = [20 20 30 40]

Their indices are  (array([0, 1, 1, 1], dtype=int32), array([2, 0, 1, 2], dtype=int32))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [18]:
import numpy as np

#In order to achieve 128 bytes need to use 4*4 array
array = np.ones((4,4))
print("%d bytes" % (array.size * array.itemsize))

128 bytes
